### ISSUE TITLE
chattier orderly_location_push() and clarity about data vs. metadata in location archive

### ISSUE THREAD

**Issue by jeffeaton** [mrc-ide/orderly2#143]
The flexibility around pushing / pulling packets in orderly2 is great. But it has left me somewhat confused about when data is being pushed around vs. only metadata.

Example: I ran several orderly reports in sequences, and then pushed the final one to a remote location. In orderly1 `orderly_push_archive()` would give me a summary of each of the dependency tasks that it was pushing before my final task.

Now when I call `orderly_location_push()`, it simply runs and returns silently:
```
> orderly2::orderly_location_push("20240618-200013-3a767016", "hiv-inference")
> 
```

This has left me unsure whether this pushed only the contents of this final task + metadata for the upstream tasks, or it also pushed the data underpinning the full dependency tree. My location (`"hiv-inference"`) was created using `orderly_init(..., require_complete_tree = TRUE)`, so I presumed it is pushing all of the data for upstream tasks; but I'm not sure how to verify that.

I think it would be helpful for `orderly2::orderly_location_push()` to (perhaps optionally) list the upstream packets, and whether they are pushed or already on the remote location.

**Comment by richfitz** [comment]
Fixed in #193
