### ISSUE TITLE
suggestion: change function name `orderly_location_pull_metadata()` to `orderly_location_metadata_update()`

### ISSUE THREAD

**Issue by jeffeaton** [mrc-ide/orderly2#146]
As I work with orderly2, I am finding the similarity of function names `orderly_location_pull_metadata()` and `orderly_location_pull_packet()` a bit confusing for myself because they sound quite similar, but do quite different things and have different signatures.

What about changing the name `orderly_location_pull_metadata()` to `orderly_location_metadata_update()` or similar? To me, 'update' captures what the function is doing more intuitively than 'pulling'.

If that change is adopted, `orderly_location_pull_packet()` could potentially be abbreviated to simply `orderly_location_pull()`.

**Comment by richfitz** [comment]
This interacts with #144, and is one of the reasons that #144 is an issue (because we can pull zero packets reasonably, even if that's unexpected)
