### ISSUE TITLE
read only archive file flag prevents file overwrite in orderly_depends()

### ISSUE THREAD

**Issue by jeffeaton** [mrc-ide/orderly2#152]
I and others are getting errors similar to this when doing `orderly_dependency()` both during interactive development and `orderly_run()`:

```
Error in `orderly2::orderly_run()`:
! Failed to run report
Caused by error:
! [EACCES] Failed to copy '/Users/jee182/Downloads/afidep-orderly-demo/mwi-raw-orderly2/archive/raw_shapefile-art/20240704-133620-b0373596/raw/mwi_ta_adm3_nso_2018_20190327.zip' to '/Users/jee182/Downloads/afidep-orderly-demo/mwi-raw-orderly2/draft/analysis_plot-raw-shapefile/20240704-133808-c6d02386/depends/raw-shapefile.zip': permission denied
Run `rlang::last_trace()` to see where the error occurred.
```

This has been difficult to troubleshoot, but I think it might be arising from the 'read only' flag on files in the archive.

The behaviour is `orderly_dependency()` works the first time, but then throws an error when called again or when `orderly_run()` is called. `unlink("<file>")` to remove the dependency before calling resolves.

I think it might be happening because the file copied from the archive is read only, and so `file.copy()` to overwrite it is blocked?  And this also happens when `orderly_run()` is called because _all_ the files are copied from the `src/` folder to `drafts/`, and so `orderly_dependency()` is trying to overwrite that?

To resolve, would it work for `orderly_dependency()` to check if the file exists, and if so `file.remove()` before the `file.copy()`?

**Comment by richfitz** [comment]
This should be fixed in #149

**Comment by plietar** [comment]
>  And this also happens when orderly_run() is called because all the files are copied from the src/ folder to drafts/, and so orderly_dependency() is trying to overwrite that?

@richfitz is this something we should fix? Don't copy files that are in the gitignore?

**Comment by jeffeaton** [comment]
Thanks, I don't think we want to restrict "don't copy files that are in the .gitignore". That would break ability to get a resource file into an orderly archive which we don't want to put into Git.

**Comment by plietar** [comment]
That's a good point. I think we can close this now that #149 is merged.

Sadly things will keep being a bit weird if you still have read-only files leftover in your `src` folders, but once you clean them up they should stop popping up.
