### ISSUE TITLE
`orderly_location_push()` by query / consistency of args with `orderly_location_pull_packet()`

### ISSUE THREAD

**Issue by jeffeaton** [mrc-ide/orderly2#155]
* `orderly_location_push()` requires specification of a `packet_id = `, but `orderly_location_pull_packet()` gives a flexible interface to pull by query.

* The argument for `orderly_location_push()` is `packet_id`, but that argument does not exist for `orderly_location_pull_packet()` and throws an error:
```
> orderly_location_pull_packet(packet_id = "20240704-215806-90fbb966")
Error in orderly_query(expr, ...) : 
  unused argument (packet_id = "20240704-215806-90fbb966")
```
(`orderly_location_pull_packet("20240704-215806-90fbb966")` works, but I can't actually figure out what the argument name that matches..)

`orderly_location_push()` requires specification of a `packet_id = `,

From using, it feels like these should be similar to each other. 

1. Can `orderly_location_push()` accept same query format?
2. Can `orderly_location_pull_packet()` and `orderly_location_push()` use the same argument when specifying a `packet_id`?

Similar to #146, it feels like the function names `orderly_location_push()` and `orderly_location_pull_packet()` should mirror each other. For me I favour shortening `orderly_location_pull_packet()` to `orderly_location_pull()` :).

**Comment by richfitz** [comment]
Fixed in #193
