### ISSUE TITLE
Clarifying phrasing in introductory vignette

### ISSUE THREAD

**Issue by lmhaile** [mrc-ide/orderly2#72]
https://github.com/mrc-ide/orderly2/blob/a0c0d6ec019693d845f9c98777ee72e50ff275e7/vignettes/introduction.Rmd#L31-L35

Also a small note I am noticing while walking through the workflow— it wasn't immediately clear to me from this statement that I should call `orderly2::orderly_init()` on an empty directory. I first tried to initalise on an entire pre-existing repository. The error message was instructive enough to resolve the issue, but I would suggest making the phrasing for this step more explicit to save others that step!

**Comment by richfitz** [comment]
Hmm, you should now call it on a pre-existing repository at least sometimes. I'll have a look and see how I can tidy this up
